---

homebrew_cask_paths:
  - /Library/Caches/Homebrew/Casks
  - /opt/homebrew-cask

apps:
  - adobe-creative-cloud
  - betterzipql
  - colorpicker-skalacolor
  - github
  - gitkraken
  - google-chrome
  - kaleidoscope
  - qlimagesize
  - qlstephen
  - sketch
  - slack
  - sublime-text
  - transmit
  - vagrant
  - virtualbox
  - visual-studio-code
