---

# this has to be run as {{ username }} or the process won't be able to run
# correctly due to permissions
- name: Open Safari
  command: su - {{ username }} -c "open /Applications/Safari.app"
  sudo: yes
  ignore_errors: yes
