---

- name: Make sure Homebrew directories exists
  file: 
    path: /usr/local/*
    state: directory
    mode: 0775
    owner: root
    group: wheel
    recurse: yes
  become: yes

- name: Download Homebrew installation script
  get_url:
    url: https://raw.githubusercontent.com/Homebrew/install/master/install
    dest: /tmp/install

- name: Install Homebrew
  shell: /usr/bin/ruby /tmp/install < /dev/null
# ðŸŽ‰ https://stackoverflow.com/a/39864317/503463


# - name: Download Homebrew
#   unarchive:
#     src: 'https://github.com/Homebrew/brew/archive/master.tar.gz'
#     dest: /tmp/
#     remote_src: yes
    
# - name: move Homebrew files to /usr/local
#   synchronize: 
#     src: /tmp/brew-master/
#     dest: /usr/local/
#   # delegate_to: "{{ inventory_hostname }}"
#   become: yes

- name: Set permissions for multiple users
  file: 
    path={{ item }}
    mode=0775
    owner=root
    group=admin
    recurse=yes
    state=directory
  become: yes
  with_items: '{{ homebrew_paths }}'
  ignore_errors: yes


- name: Fix ACL permissions for multiple users
  become: yes
  command: 'chmod -R +a "group:admin allow list,add_file,search,delete,add_subdirectory,delete_child,readattr,writeattr,readextattr,writeextattr,readsecurity,file_inherit,directory_inherit" {{ item }}'
  args:
    warn: no
  with_items: '{{ homebrew_paths }}'
  ignore_errors: yes


- name: Reset the Homebrew Library repo
  git: 
    repo=https://github.com/Homebrew/brew.git
    dest=/usr/local/Homebrew/Library
    clone=no
    update=yes
    force=yes

- name: Update Homebrew (first try may fail)
  homebrew: update_homebrew=yes
  become: no
  ignore_errors: yes

- name: Update Homebrew
  homebrew: update_homebrew=yes
  become: no
